version: '3'
services: 
  web:
    build: .
    image: vijayabharathib/fcc-dataviz-1011
    command: "npm run dev"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "8080:8080"
